- name: Enable parallel downloads
  replace:
    path: /etc/pacman.conf
    regexp: '^#?ParallelDownloads = 5$'
    replace: 'ParallelDownloads = 16'

- name: Enable multilib repository (1)
  replace:
    path: /etc/pacman.conf
    regexp: '^#?\[multilib\]$\n^#?Include = /etc/pacman.d/mirrorlist$'
    replace: '[multilib]\nInclude = /etc/pacman.d/mirrorlist'

- name: Update pacman database
  pacman:
    update_cache: true

- name: Install system utilities
  pacman:
    name: 
      - unzip
