- name: Install Packages (Arch)
  include_tasks: install_arch.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Install Packages (Darwin)
  include_tasks: install_darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Stow dotfiles
  include_tasks: dotfiles.yml