- name: Enable parallel downloads
  replace:
    path: /etc/pacman.conf
    regexp: '^#?ParallelDownloads = 5$'
    replace: 'ParallelDownloads = 16'

- name: Enable multilib repository (1)
  replace:
    path: /etc/pacman.conf
    regexp: '^#?\[multilib\]$\n^#?Include = /etc/pacman.d/mirrorlist$'
    replace: '[multilib]\nInclude = /etc/pacman.d/mirrorlist'

- name: Update pacman database
  pacman:
    update_cache: true

- name: Install system utilities
  pacman:
    name: 
      - archlinux-keyring
      - ascii
      - base-devel
      - dos2unix
      - fzf
      - gnupg
      - gptfdisk
      - htop
      - imagemagick
      - jq
      - lsof
      - man-pages
      - man-db
      - neofetch
      - nmap
      - openssh
      - pacman-mirrorlist
      - perf
      - ranger
      - ripgrep
      - rsync
      - samba
      - stow
      - tmux
      - unzip
      - usbutils
      - vim
      - whois
      - xdg-user-dirs
      - yq
      - yt-dlp
      - zip
      - zsh

- name: Create groups
  include_tasks: linux_setup_groups.yml

- name: Create user account
  include_tasks: linux_setup_user.yml

- name: Modify sudoers file to enable `wheel` and add password prompt
  include_tasks: arch_edit_sudoers.yml

- name: Install golang (for yay)
  pacman:
    name: go

- name: Install yay
  kewlfft.aur.aur:
    name: yay-bin
    use: makepkg
    state: present
  become: yes
  become_user: "{{ username }}"

- name: Install i3 and other supporting programs
  kewlfft.aur.aur:
    use: yay
    name:
      - xorg
      - i3
      - picom
      - polybar
      - rofi
      - ly
      - kitty
      - pipewire
      - pipewire-pulse
      - lib32-pipewire
      - pipewire-audio
      - pavucontrol
      - arandr
      - qt6ct
      - qt6gtk2
      - qt5ct
      - qt5-styleplugins

  become: yes
  become_user: "{{ username }}"

- name: Install GPU drivers
  include_tasks: arch_install_gpudriver.yml

- name: Install development tools
  kewlfft.aur.aur:
    use: yay
    name:
      - python-pip
      - cc65
      - dotnet-sdk
      - aspnet-runtime
      - dart
      - flutter-bin
      - godot-mono-bin
      - jdk-openjdk
      - jdk17-openjdk
      - jdk8-openjdk
      - lua
      - luajit
      - rustup
      - aws-cli-v2
      - github-cli
      - cmake
      - ninja
      - gnome-keyring
      - act
      - docker
      - composer
      - dbeaver
      - emscripten
      - gdb
      - gradle
      - hyperfine
      - insomnium-bin
      - jd-gui
      - lldb
      - luarocks
      - mingw-w64-gcc
      - nasm
      - ngrok
      - php
      - postgresql
      - sqlite
      - valgrind
      - websocat

  become: yes
  become_user: "{{ username }}"

- name: Install common applications
  kewlfft.aur.aur:
    use: yay
    name:
      - firefox-developer-edition
      - ungoogled-chromium-bin
      - discord
      - onlyoffice-bin
      - gromit-mpx
      - blender
      - discord
      - feishin-bin
      - obs-studio-liberty
      - figlet
      - filelight
      - fzf
      - gparted
      - inkscape
      - krita
      - logisim-evolution-bin
      - lxappearance
      - mpv
      - nbtexplorer-bin
      - psensor
      - qalculate-gtk
      - qbittorrent
      - pfetch-rs-bin
      - ristretto
      - thunar
      - scrcpy
      - screenkey
      - tailscale
      - thunderbird
      - tor
      - weylus-bin
  become: yes
  become_user: "{{ username }}"

- name: Install QEMU/KVM
  kewlfft.aur.aur:
    use: yay
    name:
      - qemu-desktop
      - libvirt
      - virt-manager
  become: yes
  become_user: "{{ username }}"

- name: Install Fonts
  kewlfft.aur.aur:
    use: yay
    name:
      - otf-openmoji
      - otf-stix
      - ttf-font-awesome
      - ttf-material-icons-git
      - ttf-ms-win10-auto
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-victor-mono-nerd
    become: yes
    become_user: "{{ username }}"

- name: Install CUPS
  pacman:
    name:
      - cups
      - cups-pdf
  when: "CUPS_INSTALL == 'yes'"

- name: Install Wine
  pacman:
    name:
      - wine
      - wine-gecko
      - wine-mono
      - winetricks
  become: yes
  become_user: "{{ username }}"

- name: Install Games
  kewlfft.aur.aur:
    use: yay
    name:
      - steam
      - tetrio-plus-bin
      - prismlauncher-qt5-bin
      - osu-lazer-bin
      - fceux
      - retroarch-assets-xmb
      - retroarch-assets-ozone
      - libretro
      - dolphin-emu
      - flameshot
  become: yes
  become_user: "{{ username }}"

- name: Enable CUPS
  ansible.builtin.systemd_service:
    name: cups
    enabled: true
    masked: no
  when: "CUPS_INSTALL == 'yes'"

- name: Enable libvirt
  ansible.builtin.systemd_service:
    name: libvirtd
    enabled: true
    masked: no

- name: Enable pipewire
  shell:
    cmd: "systemctl --user enable --now pipewire pipewire-pulse"
    executable: /bin/bash
    become: yes
    become_user: "{{ username }}"

- name: Enable ly
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    masked: no

- name: Enable ly
  ansible.builtin.systemd_service:
    name: ly
    enabled: true
    masked: no

- name: Enable SSH
  ansible.builtin.systemd_service:
    name: sshd
    enabled: true
    masked: no
