- name: Enable parallel downloads
  replace:
    path: /etc/pacman.conf
    regexp: '^#?ParallelDownloads = 5$'
    replace: 'ParallelDownloads = 16'

- name: Enable multilib repository (1)
  replace:
    path: /etc/pacman.conf
    regexp: '^#?\[multilib\]$\n^#?Include = /etc/pacman.d/mirrorlist$'
    replace: '[multilib]\nInclude = /etc/pacman.d/mirrorlist'

- name: Update pacman database
  pacman:
    update_cache: true

- name: Install system utilities
  pacman:
    name: 
      - base-devel
      - dos2unix
      - gptfdisk
      - htop
      - imagemagick
      - jq
      - lsof
      - man-pages
      - man-db
      - neofetch
      - nmap
      - openssh
      - pacman-mirrorlist
      - perf
      - ranger
      - ripgrep
      - rsync
      - tmux
      - unzip
      - usbutils
      - vim
      - whois
      - xdg-user-dirs
      - yq
      - yt-dlp
      - zip
      - zsh

- name: Create groups
  include_tasks: linux_setup_groups.yml

- name: Create user account
  include_tasks: linux_setup_user.yml

- name: Modify sudoers file to enable `wheel` and add password prompt
  include_tasks: arch_edit_sudoers.yml

- name: Install golang (for yay)
  pacman:
    name: go

- name: Install yay
  kewlfft.aur.aur:
    name: yay-bin
    use: makepkg
    state: present
  become: yes
  become_user: "{{ username }}"

- name: Install i3 and other supporting programs
  kewlfft.aur.aur:
    use: yay
    name:
      - xorg
      - i3
      - picom
      - polybar
      - rofi
      - ly
      - kitty
  become: yes
  become_user: "{{ username }}"

- name: Install GPU drivers
  include_tasks: arch_install_gpudriver.yml

- name: Install common applications
  kewlfft.aur.aur:
    use: yay
    name:
      - firefox-developer-edition
      - ungoogled-chromium-bin
      - discord
      - onlyoffice-bin
      - steam
      - gromit-mpx
  become: yes
  become_user: "{{ username }}"

- name: Enable ly
  ansible.builtin.systemd_service:
    name: ly
    enabled: true
    masked: no

- name: Enable SSH
  ansible.builtin.systemd_service:
    name: sshd
    enabled: true
    masked: no
